# File name: test.kv
<VKeyboard>:
    height: 500
    
<MyscreenApp>:    
    orientation:'vertical'
    btx:_sta_btn
    tlb:_time_lab
        
    GridLayout:
        cols: 3
        spacing:10
        padding:10,40,10,10
        row_force_default:True
        row_default_height:58
        Button:
            id:_sta_btn
            text: '状态'
            font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
            color: .8,.9,0,1
            font_size: 32               
        Button:
            text: '可运行'
            font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
            pos: 100,0
            size: 100, 50
            color: .8,.9,0,.2
            font_size: 32
        Button:
            id:_k_btn
            text: '控制杆'
            font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
            color: .8,.6,0,1
            font_size: 32
            background_color:1,0,0,.3
            
    GridLayout:
        cols: 3
        spacing:10
        padding:10,10,10,60
        row_force_default:True
        row_default_height:68

        Label:
            text:'面条长度'
            font_size: 32
            font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
            background_color:1,0,1,.1

        Label:
            id:_time_lab
            text:'时间'
            font_size: 40
            font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
            canvas:
                Color:
                    rgba:0,1,0,.1
                Rectangle:
                    pos: self.pos
                    size: self.size
        Label:
            id:_fs_lab
            text:'份数'
            font_size: 40
            font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'            
            canvas:
                Color:
                    rgba:0,1,0,.5
                Line:
                    circle: self.pos[0],self.pos[1],50
        Spinner:
            id:sp_btn
            text: 'Ho1'
            font_size: 40
            size_hine:None,None
            size:100,40
            values:{'1','2','3','4','5','6','7','8','9','10','11','4','5','2','3','4','5','2','3','4','5'}
            on_release:root.show_selected_value(sp_btn)
        TextInput:
            text: '65'
            multiline:False
            font_size: 40
            padding:40,10,10,0            
        TextInput:
            text: '1'
            text_align: "center"
            multiline:False
            font_size: 40
            padding:40,10,10,0  
            
    ToggleButton:
        id:tg_btn
        text: 'switch'
        color: .8,.9,0,1
        font_size: 40
        on_press:root.press_callback(tg_btn)

    GridLayout:
        cols: 3
        spacing:10
        padding:10
        
        Button:
            text:'滚筒'
            font_size: 40
            font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
            color: .8,.9,0,1
            font_size: 32
        Button:
            text:'水泵'
            font_size: 40
            font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
            pos: 0, 100
            size: 100, 50
            color: .8,.9,0,1
            font_size: 32
        Button:
            text:'漏斗'
            font_size: 40
            font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
            color: .8,.9,0,1
            font_size: 32
