# File name: test.kv
<VKeyboard>:
	height: 500

<MyscreenApp>:
	orientation:'vertical'
	lb1:_lb_1
	lb2:_lb_2
	lb3:_lb_3
	txt1:_txt1
	txt2:_txt2
	txt3:_txt3
		
	GridLayout:
		cols: 3
		spacing:10
		padding:10,50,10,10
		row_force_default:True
		row_default_height:58
		Label:
			id:_lb_1
			text: '状态'
			font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
			color: .8,.9,0,1
			font_size: 32
			bkcolor:[1,0,0,.5]
			canvas:
				Color:
					rgba:self.bkcolor
				Ellipse:
					pos:self.pos[0]+self.size[0]/7,self.pos[1]-self.size[0]/6
					size:self.size[0]*0.75,self.size[0]*0.7
		Label:
			id:_lb_2
			text: '可运行'
			font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
			color: .8,.9,0,.2
			font_size: 32
			bkcolor:[1,0,0,.5]
			canvas:
				Color:
					rgba:self.bkcolor
				Ellipse:
					pos:self.pos[0]+self.size[0]/7,self.pos[1]-self.size[0]/6
					size:self.size[0]*0.75,self.size[0]*0.7
		Label:
			id:_lb_3
			text: '控制杆'
			font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
			color: .8,.6,0,1
			font_size: 32
			bkcolor:[1,0,0,.5]
			canvas:
				Color:
					rgba:self.bkcolor
				Ellipse:
					pos:self.pos[0]+self.size[0]/7,self.pos[1]-self.size[0]/6
					size:self.size[0]*0.75,self.size[0]*0.7
			
	GridLayout:
		cols: 3
		spacing:10
		padding:10,0,10,60
		row_force_default:True
		row_default_height:68

		Label:
			text:'面条长度'
			font_size: 32
			font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
		Label:
			text:'时间'
			font_size: 40
			font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
		Label:
			text:'份数'
			font_size: 40
			font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'

		TextInput:
			id:_txt1
			text: '55'
			multiline:False
			font_size: 40
			padding:40,10,10,0
			on_text_validate:root.on_enter(self.text)
		TextInput:
			id:_txt2
			text: '12'
			multiline:False
			font_size: 40
			padding:40,10,10,0
			on_text_validate:root.on_enter(self.text)
		TextInput:
			id:_txt3
			text: '1'
			multiline:False
			font_size: 40
			padding:40,10,10,0
			on_text_validate:root.on_enter(self.text)
			
	ToggleButton:
		id:tg_btn
		text: 'switch'
		color: .8,.9,0,1
		font_size: 40
		on_press:root.press_callback(tg_btn)

	GridLayout:
		cols: 3
		spacing:10
		padding:10
		
		Button:
			id:_btn_b1
			text:'滚筒'
			font_size: 40
			font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
			color: .8,.9,0,1
			font_size: 32
			on_press:root.press_btn_b1(_btn_b1)
		Button:
			id:_btn_b2
			text:'水泵'
			font_size: 40
			font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
			pos: 0, 100
			size: 100, 50
			color: .8,.9,0,1
			font_size: 32
			on_press:root.press_btn_b2(_btn_b2)
		Button:
			id:_btn_b3
			text:'漏斗'
			font_size: 40
			font_name:'/usr/share/fonts/truetype/wqy/wqy-microhei.ttc'
			color: .8,.9,0,1
			font_size: 32
			on_release:root.press_btn_b3(_btn_b3)
